ARG IMAGE_TO_TEST=miniforge3
FROM ${IMAGE_TO_TEST}

CMD [ "/bin/bash" ]

RUN mkdir -p /tmp && \
    ls -lah /tmp
COPY ./tests /tmp/tests
RUN ls -lah /tmp
RUN set -e; \
    ls -lah /tmp/tests/*; \
    for f in /tmp/tests/*; do \
        echo "Executing $f"; \
        $f; \
    done
