name: docker-build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: null

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.cfg.MINIFORGE_NAME }}:${{ matrix.cfg.MINIFORGE_VERSION }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - MINIFORGE_NAME: "Miniforge3"
            MINIFORGE_VERSION: "26.3.2-3"
            DOCKERFILE: "ubuntu"
    env:
      MINIFORGE_NAME: ${{ matrix.cfg.MINIFORGE_NAME }}
      MINIFORGE_VERSION: ${{ matrix.cfg.MINIFORGE_VERSION }}
      DOCKERFILE: ${{ matrix.cfg.DOCKERFILE }}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
        with:
          platforms: arm64,amd64,ppc64le

      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: build and test image
        shell: bash
        run: |
          set -euxo pipefail

          docker buildx ls
          docker buildx create --use --platform linux/arm64,linux/amd64,linux/ppc64le
          
          # Build the image for all platforms and store the final result in the build cache.
          # All the later steps will pick this up from the cache.
          docker buildx build \
            --platform linux/arm64,linux/amd64,linux/ppc64le \
            -f ${DOCKERFILE}/Dockerfile \
            --build-arg MINIFORGE_NAME \
            --build-arg MINIFORGE_VERSION \
            .
          
          # As we need to fallback to the docker builder to run the tests, we cannot run all tests at once.
          for platform in "linux/arm64" "linux/amd64" "linux/ppc64le"; do
            docker buildx build \
              --platform ${platform} \
              -f ${DOCKERFILE}/Dockerfile \
              --build-arg MINIFORGE_NAME \
              --build-arg MINIFORGE_VERSION \
              -t localforge \
              --load \
              .
            
            # We need to use the docker builder instead of the docker-container builder to fetch from local registry.
            docker buildx build \
              --platform ${platform} \
              -f tests/Dockerfile.root \
              --build-arg IMAGE_TO_TEST=localforge \
              --builder default \
              tests/
          done        

      - name: deploy
        if: github.ref == 'refs/heads/main' && github.repository == 'conda-forge/miniforge-images'
        env:
          CFD_QUAY_PASSWORD: ${{ secrets.CF_DAEMON_QUAY_PASSWORD }}
          DH_PASSWORD: ${{ secrets.CF_BOT_DH_PASSWORD }}
        run: |
          set -euxo pipefail

          # login
          docker login -u condaforgebot -p ${DH_PASSWORD}
          docker login -u conda_forge_daemon -p ${CFD_QUAY_PASSWORD} quay.io

          # push the images
          for registry in "" "quay.io/"; do
            docker buildx build \
              --platform linux/arm64,linux/amd64,linux/ppc64le \
              -f ${DOCKERFILE}/Dockerfile \
              --build-arg MINIFORGE_NAME \
              --build-arg MINIFORGE_VERSION \
              -t ${registry}condaforge/${MINIFORGE_NAME/M/m}:latest \
              --push \
              .
            
            docker buildx build \
              --platform linux/arm64,linux/amd64,linux/ppc64le \
              -f ${DOCKERFILE}/Dockerfile \
              --build-arg MINIFORGE_NAME \
              --build-arg MINIFORGE_VERSION \
              -t ${registry}condaforge/${MINIFORGE_NAME/M/m}:${MINIFORGE_VERSION} \
              --push \
              .
          done

  build-success:
    name: build success
    runs-on: ubuntu-slim
    needs: build
    steps:
      - name: notify build success
        run: echo "Build was successful!"
